name: "Labels: PR"

on:
- pull_request

jobs:
  labeler:
    if: github.actor != 'PJBot'
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # Harmony start
    - name: Automatic Maintenance Label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.pull_request.title, 'Harmony') || startsWith(github.event.pull_request.title, 'Changelog') }} #Box change, look for Harmony instead of Upstream
      with:
        labels: Maintenance
    - uses: snnaplab/get-labels-action@v1.0.1
      continue-on-error: true
    # Harmony end
    - uses: actions/labeler@v5
      # Harmony start
      if: ${{ (env.LABELS == '') || (! contains(env.LABELS, 'Maintenance')) }}
      with:
        sync-labels: true
        # Add repository token because it kept breaking, Box change
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      # Harmony end
